### ISSUE TITLE
Injection

### ISSUE THREAD

**Issue by rose1337** [guttir14/SoT-Hook#1]
What u using for injection? Trying to use xenos with mmap, but getting crash, using native injection, have error 0x000000135

**Comment by guttir14** [comment]
I use processhacker loadlibrary

**Comment by rose1337** [comment]
thanks buddy

**Comment by rose1337** [comment]
Why i don't have 'load module?'
![image](https://user-images.githubusercontent.com/43756332/96178418-d1fcce00-0f48-11eb-995b-3b3e75a67e81.png)

**Comment by guttir14** [comment]
> Why i don't have 'load module?'
> ![image](https://user-images.githubusercontent.com/43756332/96178418-d1fcce00-0f48-11eb-995b-3b3e75a67e81.png)

download Nightly version of process hacker from official website:
https://processhacker.sourceforge.io/downloads.php

**Comment by guttir14** [comment]
As of today update you can use 'Loader'
