### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by Falghere** [guttir14/SoT-Hook#10]
I am very noob with these things, could you help me and say what has to be done to correct this error?

![image](https://user-images.githubusercontent.com/16209066/100615151-f09b0680-32f5-11eb-81f4-422c2fd69c57.png)

**Comment by Falghere** [comment]
I fix the warnings, but this one I can't get it at all

![image](https://user-images.githubusercontent.com/16209066/100615207-0a3c4e00-32f6-11eb-8827-b4c8f3edc3ac.png)

**Comment by Falghere** [comment]
now i cant compile the hook because he need zydis

![image](https://user-images.githubusercontent.com/16209066/100620948-cc432800-32fd-11eb-9bfa-9a607fee5c8d.png)

**Comment by guttir14** [comment]
`.\HookLib\HookLib\Zydis\msvc\bin\ReleaseX64\Zydis.lib`
