### ISSUE TITLE
compiling issue with hooklib?

### ISSUE THREAD

**Issue by 1C3M4N3** [guttir14/SoT-Hook#12]
1>HookLib.lib(HookLib.obj) : error LNK2001: unresolved external symbol __imp_ExAllocatePoolWithTag
1>HookLib.lib(HookLib.obj) : error LNK2001: unresolved external symbol __imp_ExFreePoolWithTag
1>HookLib.lib(HookLib.obj) : error LNK2001: unresolved external symbol __imp_MmProbeAndLockPages
1>HookLib.lib(HookLib.obj) : error LNK2001: unresolved external symbol __imp_MmUnlockPages
1>HookLib.lib(HookLib.obj) : error LNK2001: unresolved external symbol __imp_MmProtectMdlSystemAddress
1>HookLib.lib(HookLib.obj) : error LNK2001: unresolved external symbol __imp_MmMapLockedPagesSpecifyCache
1>HookLib.lib(HookLib.obj) : error LNK2001: unresolved external symbol __imp_MmUnmapLockedPages
1>HookLib.lib(HookLib.obj) : error LNK2001: unresolved external symbol __imp_IoAllocateMdl
1>HookLib.lib(HookLib.obj) : error LNK2001: unresolved external symbol __imp_IoFreeMdl

as far as im aware hooklib.lib compiled correctly

**Comment by egssy0** [comment]
Too many people opened same issue, Please read README.md or just go down of the page.
Read **Dependences** Section, You must link HookLib.lib path in your Project

**Comment by guttir14** [comment]
Compile HookLib in 'Release' mode, not in 'Release Kernel'
