### ISSUE TITLE
LNK1181	cannot open input file 'HookLib.lib'

### ISSUE THREAD

**Issue by hdhdhfhfirjf** [guttir14/SoT-Hook#2]
trying to build the source to use the cheat and im getting this error have no idea how to fix

LNK1181	cannot open input file 'HookLib.lib'

**Comment by guttir14** [comment]
build [HookLib](https://github.com/HoShiMin/HookLib) and put .lib file into 'lib' folder

**Comment by Naskel-Ross** [comment]
When I try to compile HookLib, I get these errors
![devenv_AMDtzbqz7g](https://user-images.githubusercontent.com/60135751/97107199-5f71b800-16d7-11eb-8990-8814bff63af5.png)
