### ISSUE TITLE
Can you add a ready-made HookLib.lib to git?

### ISSUE THREAD

**Issue by Naskel-Ross** [guttir14/SoT-Hook#6]
Build error HookLib
![devenv_AMDtzbqz7g](https://user-images.githubusercontent.com/60135751/97109486-7ff43f00-16e4-11eb-8d93-05d5c9ac7f59.png)

**Comment by guttir14** [comment]
I can't according to the UnKnoWnCheaTs rules. Compiled library may contain malware code

**Comment by Naskel-Ross** [comment]
Can u help me in discord? I constantly getting errors
😈ℕ𝕒𝕤𝕜𝕖𝕝_ℝ𝕠𝕤𝕤😈#1337
