### ISSUE TITLE
gameWindow is zero

### ISSUE THREAD

**Issue by NtLoadDriverEx** [guttir14/SoT-Hook#7]
After injecting successfully into the game with this logged:
#
[log.txt](https://github.com/guttir14/SoT-Hook/files/5442004/log.txt)
gameWindow is zero?
https://github.com/guttir14/SoT-Hook/blob/670aa22d30957193a27a3cf6c4ae7c989de82430/Cheat/cheat.cpp#L258-L263

I can't imagine this actually being null. Any reason why this is?

**Comment by guttir14** [comment]
Is it steam version?

**Comment by NtLoadDriverEx** [comment]
it is Microsoft store version. What reason in particular causes the UWP version to fail? something to do with application frame host being used as the window.

**Comment by guttir14** [comment]
There are some difficulties with UWP apps. First, for some reason output window equals 0, when getting swapchain description, and second, there are no input messages are sent to window callback function, also UWP doesn't have full access to filesystem, only to its own folders. I pushed a temporary fix that should give atleast working esp for now.

**Comment by NtLoadDriverEx** [comment]
I can look into the porting of it to the microsoft version as that would interest me the most, if you would like to add me on discord I can update you sooner about my findings and we can get it resolved asap :) 

Discord: Exceptis#0001
